### PR TITLE
Complete

### PR DESCRIPTION
**Pull request by greenitthe**
Scope was a neat one. 12/10

### CODE REVIEW

**Comment by greenitthe** [comment]
Test failing despite having completed all. Is Travis configured correctly?

javascriptingbuildfailing

**Comment by greenitthe** [comment]
@barberboy

**Comment by barberboy** [comment]
Hmmm, intriguing... I'm looking into it now.

**Comment by barberboy** [comment]
Ahh... The exercise tells you to create a folder called "javascripting" and put your work in there. But there are already (empty) stub files in the top level, and the tests are testing against those files.

To make the tests pass, move the files in `javascripting` into the top level directory.

``` sh
mv javascripting/* .
rmdir javascripting
npm test
```

**Comment by greenitthe** [comment]
@barberboy Huzzah! Tests be passing!

**Review by barberboy — APPROVED** [review]
Looks great! 👍  💯

**Pull request closed without merging**
